
package:
  name: ska.sun  # lower case name of package, may contain '-' but no spaces
  version: {{ GIT_DESCRIBE_TAG }}


build:
  script: "pip install --no-deps --verbose --no-binary :all: --no-index --egg ."
  noarch: python
  preserve_egg_dir: yes
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Sun



requirements:
  build:
    - pip <10.0
    - python
    - setuptools
    - quaternion
    - chandra.time
    - ska.quatutil
    - numpy
  run:
    - python
    - ska.quatutil
    - chandra.time
    - quaternion
    - numpy

test:
  imports:
    - Ska.Sun

about:
  home: https://github.com/sot/Ska.Sun
