package:
  name: acdc
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/acdc


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - pip
    - setuptools
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - jinja2
    - numpy
    - astropy
    - pytest
    - agasc
    - chandra_aca
    - chandra.time
    - mica
    - pyyaks
    - quaternion
    - ska.engarchive
    - ska.file
    - ska.sun
    - testr

test:
  imports:
    - acdc


about:
  home: git@github.com:sot/acdc

