package:
  name: kadi
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/kadi


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - six
    - numpy
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - pytables
    - configobj
    - requests
    - tables3_api
    - django
    - pyyaks
    - ska.dbi
    - ska.file
    - ska.ftp
    - ska.numpy
    - astropy
    - quaternion
    - chandra.time
    - ska.engarchive
    - chandra.cmd_states
    - numpy
    - parse_cm
    - testr


test:
  imports:
    - kadi


about:
  home: https://github.com/sot/kadi
  license: BSD
  summary: kadi
