package:
  name: acis_thermal_check
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/acis_thermal_check


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - numpy
    - matplotlib
    - pytest
    - jinja2
    - requests
    - docutils
    - astropy
    - backstop_history
    - chandra.cmd_states
    - chandra.time
    - kadi
    - ska.dbi
    - ska.engarchive
    - ska.file
    - ska.numpy
    - ska.matplotlib
    - ska.parsecm
    - ska.sun
    - ska.shell
    - testr
    - xija


test:
  imports:
    - acis_thermal_check

about:
  home: https://github.com/acisops/acis_thermal_check

