package:
  name: starcheck
  version:  {{ SKA_PKG_VERSION }}

build:
  number: 0
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/starcheck


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - pip
    - setuptools
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - chandra_aca
    - hopper
    - agasc
    - ska.matplotlib
    - testr

test:
  imports:
    - starcheck


about:
  home: https://github.com/sot/starcheck

