package:
  name: tables3_api
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/tables3_api


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - pytables
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - pytables
    - testr

test:
  imports:
    - tables3_api


about:
  home: https://github.com/sot/tables3_api

