package:
  name: acis_taco
  version:  {{ SKA_PKG_VERSION }}

build:

source:
  path: {{ SKA_TOP_SRC_DIR }}/acis_taco


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python

  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - numpy
    - matplotlib
    - ska.quatutil
    - chandra.time
    - ska.matplotlib
    - ska.sun
    - quaternion
    - ska.engarchive
    - testr

test:
  imports:
    - acis_taco

about:
  home: https://github.com/sot/taco

