
package:
  name: ska.shell  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}

build:
  noarch: python
  preserve_egg_dir: yes
  script: python setup.py install

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Shell

requirements:
  build:
    - python
    - six

  run:
    - python
    - six
    - pexpect
    - testr
    - ska_helpers

test:
  imports:
    - Ska.Shell

about:
  home: https://github.com/sot/Ska.Shell

