package:
  name: ska.matplotlib  # lower case name of package, may contain '-' but no spaces
  version: {{ GIT_DESCRIBE_TAG }}


build:
  script: "pip install --no-deps --verbose --no-binary :all: --no-index --egg ."
  noarch: python
  preserve_egg_dir: yes
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Matplotlib



requirements:
  build:
    - pip <10.0
    - python
    - six
    - matplotlib
    - chandra.time
    - numpy

  run:
    - python
    - six
    - matplotlib
    - chandra.time
    - numpy

test:
  imports:
    - Ska.Matplotlib

about:
  home: https://github.com/sot/Ska.Matplotlib
