package:
  name: psmc_check
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python
  script_env:
     - SKA

source:
  path: {{ SKA_TOP_SRC_DIR }}/psmc_check


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - six
    - numpy
    - matplotlib
    - acis_thermal_check
    - xija
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - numpy
    - matplotlib
    - acis_thermal_check
    - xija

test:
  imports:
    - psmc_check

about:
  home: https://github.com/acisops/psmc_check

