package:
  name: proseco
  version:  {{ SKA_PKG_VERSION }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/proseco


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - pip
    - setuptools
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - scipy
    - astropy
    - chandra_aca
    - agasc
    - mica
    - testr

test:
  imports:
    - proseco


about:
  home: https://github.com/sot/proseco

