package:
  name: ska.matplotlib  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  script: python setup.py install
  noarch: python
  preserve_egg_dir: yes

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Matplotlib



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  run:
    - python
    - six
    - matplotlib
    - chandra.time
    - numpy

test:
  imports:
    - Ska.Matplotlib

about:
  home: https://github.com/sot/Ska.Matplotlib
