
package:
  name: ska.sun  # lower case name of package, may contain '-' but no spaces
  version: {{ GIT_DESCRIBE_TAG }}


build:
  noarch: python
  preserve_egg_dir: yes

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Sun



requirements:
  build:
    - python
    - quaternion
    - chandra.time
    - ska.quatutil
    - numpy
  run:
    - python
    - ska.quatutil
    - chandra.time
    - quaternion
    - numpy

test:
  imports:
    - Ska.Sun

about:
  home: https://github.com/sot/Ska.Sun
