
package:
  name: ska.sun  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  preserve_egg_dir: yes

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Sun



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - ska.quatutil
    - chandra.time
    - quaternion
    - numpy

test:
  imports:
    - Ska.Sun

about:
  home: https://github.com/sot/Ska.Sun
