package:
  name: ska.file  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  preserve_egg_dir: yes

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.File



requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  run:
    - python


test:
  imports:
    - Ska.File

about:
  home: https://github.com/sot/Ska.File
