package:
  name: ska.file  # lower case name of package, may contain '-' but no spaces
  version: {{ GIT_DESCRIBE_TAG }}


build:
  noarch: python
  preserve_egg_dir: yes

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.File



requirements:
  build:
    - python

  run:
    - python


test:
  imports:
    - Ska.File

about:
  home: https://github.com/sot/Ska.File
