package:
  name: ska3-win
  version: 0.9

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
  # Ska packages
   - agasc
   - annie
   - acisfp_check
   - acis_taco
   - acis_thermal_check
   - backstop_history
   - chandra.cmd_states
   - chandra.maneuver
   - chandra.time
   - chandra_aca
   - cxotime
   - dea_check
   - dpa_check
   - hopper
   - kadi
   - maude
   - mica
   - parse_cm
   - psmc_check
   - quaternion
   - ska.arc5gl
   - ska.astro
   - ska.dbi
   - ska.engarchive
   - ska.file
   - ska.ftp
   - ska.matplotlib
   - ska.numpy
   - ska.parsecm
   - ska.quatutil
   - ska.shell
   - ska.sun
   - ska.tdb
   - ska3-template
   - ska_path
   - ska_sync
   - pyyaks
   - testr
   - xija

   # Adapted from the list from M. Baski pkgs3.conda
   # (see email Windows Python install script Nov 14 2019)
   - astropy
   - beautifulsoup4
   - configobj
   - cryptography
   - cython
   - decorator
   - docutils
   - ipyparallel
   - notebook
   - jinja2
   - jpeg
   - jupyter
   - libtiff
   - lxml
   - matplotlib
   - networkx
   - nose
   - numba
   - numpy =1.12.1
   - openssl
   - pandas
   - paramiko
   - pep8
   - pillow
   - ply
   - psutil
   - pycrypto
   - pyflakes
   - pygments
   - pyparsing
   - pyqt
   - pytest
   - python =3.8.1
   - python-dateutil
   - pytz
   - pyyaml
   - pyzmq
   - qt
   - requests
   - runipy
   - scipy
   - six
   - sphinx
   - sqlalchemy
   - sqlite
   - yaml
   - zlib
   - setuptools
   - conda
   - conda-env
   - pip
   - libpng
   - cffi
   - mistune
   - py
   - pycparser
   - tornado
   - markupsafe
   - h5py
   - numexpr
   - pytables
   - git
   - ipython=6.1.0
   - pylint
   - conda-build