package:
  name: chandra.cmd_states
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  preserve_egg_dir: yes # (default no)

source:
  path: {{ SKA_TOP_SRC_DIR }}/Chandra.cmd_states


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - chandra.time
    - ska.dbi
    - ska.file
    - chandra.maneuver
    - quaternion
    - ska.sun
    - ska.parsecm
    - ska.numpy
    - ska.ftp
#    - kadi
    - testr

test:
  imports:
    - Chandra.cmd_states


about:
  home: https://github.com/sot/cmd_states
