package:
  name: ska.dbi
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python
  preserve_egg_dir: yes # (default no)

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.DBI


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - six
    - sqlite
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - sqlite
    - pytest
    - numpy
    - testr

test:
  imports:
    - Ska.DBI

about:
  home: https://github.com/sot/Ska.DBI


