package:
  name: ska_path  # lower case name of package, may contain '-' but no spaces
  version: {{ GIT_DESCRIBE_TAG }}


build:
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_path



requirements:
  build:
    - pip
    - python
  run:
    - python


test:
  imports:
    - ska_path

about:
  home: https://github.com/sot/ska_path
