package:
  name: ska.numpy
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  script: "pip install --no-deps --verbose --no-binary :all: --no-index --egg ."
  script_env:
    - SKA_TOP_SRC_DIR
  preserve_egg_dir: yes # (default no)

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Numpy


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip <10.0
    - python
    - setuptools
    - numpy
    - cython
    - six
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - setuptools
    - six
    - numpy
    - nose
    - testr

test:
  imports:
    - Ska.Numpy


about:
  home: https://github.com/sot/Ska.Numpy

