---
package:
  name: ska3-core
  version: 2020.11

  requirements:
    run:
      - _libgcc_mutex ==0.1  # [linux]
      - alabaster ==0.7.12
      - appnope ==0.1.0  # [osx]
      - asgiref ==3.2.10
      - astroid ==2.4.2
      - astropy ==4.0.1.post1
      - astropy-healpix ==0.5
      - astropy-sphinx-theme ==1.1
      - attrs ==19.3.0
      - autopep8 ==1.5.3
      - babel ==2.8.0
      - backcall ==0.2.0
      - bcrypt ==3.1.7
      - beautifulsoup4 ==4.9.1
      - blas ==1.0
      - bleach ==3.1.5
      - blinker ==1.4
      - blosc ==1.19.0
      - bokeh ==2.1.1
      - brotlipy ==0.7.0
      - bzip2 ==1.0.8
      - ca-certificates ==2020.6.24
      - certifi ==2020.6.20
      - cffi ==1.14.0
      - chardet ==3.0.4
      - conda ==4.8.3
      - conda-build ==3.18.11
      - conda-package-handling ==1.6.1
      - configobj ==5.0.6
      - cryptography ==2.9.2
      - cycler ==0.10.0
      - cython ==0.29.21
      - dbus ==1.13.16
      - decorator ==4.4.2
      - defusedxml ==0.6.0
      - django ==3.0.3
      - docutils ==0.16
      - docxtpl ==0.10.0
      - entrypoints ==0.3
      - expat ==2.2.9
      - filelock ==3.0.12
      - flake8 ==3.8.3
      - fontconfig ==2.13.0  # [linux]
      - freetype ==2.10.2
      - gettext ==0.19.8.1  # [osx]
      - gitdb ==4.0.5
      - gitpython ==3.1.3
      - glib ==2.65.0
      - glob2 ==0.7
      - gst-plugins-base ==1.14.0  # [linux]
      - gstreamer ==1.14.0  # [linux]
      - h5py ==2.10.0
      - hdf5 ==1.10.4
      - icu ==58.2
      - idna ==2.10
      - imagesize ==1.2.0
      - importlib-metadata ==1.7.0
      - importlib_metadata ==1.7.0
      - intel-openmp ==2020.1  # [linux]
      - intel-openmp ==2020.1  # [linux]
      - ipykernel ==5.3.3
      - ipyparallel ==6.3.0
      - ipython ==7.16.1
      - ipython_genutils ==0.2.0
      - ipywidgets ==7.5.1
      - isort ==4.3.21
      - jedi ==0.17.1
      - jinja2 ==2.11.2
      - jira ==2.0.0
      - joblib ==0.16.0
      - jpeg ==9b
      - jplephem ==2.14
      - json5 ==0.9.5
      - jsonschema ==3.2.0
      - jupyter ==1.0.0
      - jupyter_client ==6.1.6
      - jupyter_console ==6.1.0
      - jupyter_core ==4.6.3
      - jupyterlab ==2.1.5
      - jupyterlab_server ==1.2.0
      - kiwisolver ==1.2.0
      - lazy-object-proxy ==1.4.3
      - lcms2 ==2.11
      - ld_impl_linux-64 ==2.33.1  # [linux]
      - libarchive ==3.4.2
      - libcxx ==10.0.0  # [osx]
      - libedit ==3.1.20191231
      - libffi ==3.3
      - libgcc-ng ==9.1.0  # [linux]
      - libgfortran ==3.0.1  # [osx]
      - libgfortran-ng ==7.3.0  # [linux]
      - libiconv ==1.16  # [osx]
      - liblief ==0.10.1
      - libllvm9 ==9.0.1
      - libpng ==1.6.37
      - libsodium ==1.0.18
      - libstdcxx-ng ==9.1.0  # [linux]
      - libtiff ==4.1.0
      - libuuid ==1.0.3  # [linux]
      - libxcb ==1.14  # [linux]
      - libxml2 ==2.9.10
      - libxslt ==1.1.34
      - line_profiler ==2.1.2
      - llvm-openmp ==10.0.0  # [osx]
      - llvmlite ==0.33.0
      - lxml ==4.5.2
      - lz4-c ==1.9.2
      - lzo ==2.10
      - markupsafe ==1.1.1
      - matplotlib ==3.2.2
      - matplotlib-base ==3.2.2
      - mccabe ==0.6.1
      - mistune ==0.8.4
      - mkl ==2020.1  # [linux]
      - mkl ==2020.1  # [linux]
      - mkl-service ==2.3.0
      - mkl_fft ==1.1.0
      - mkl_random ==1.1.1
      - mock ==4.0.2
      - more-itertools ==8.4.0
      - mpld3 ==0.3
      - nb_conda ==2.2.1
      - nb_conda_kernels ==2.2.3
      - nbconvert ==5.6.1
      - nbformat ==5.0.7
      - ncurses ==6.2
      - networkx ==2.4
      - nose ==1.3.7
      - notebook ==6.0.3
      - numba ==0.50.1
      - numexpr ==2.7.1
      - numpy ==1.18.5
      - numpy-base ==1.18.5
      - numpydoc ==1.1.0
      - oauthlib ==3.1.0
      - olefile ==0.46
      - openssl ==1.1.1g
      - packaging ==20.4
      - pandas ==1.0.5
      - pandoc ==2.10
      - pandocfilters ==1.4.2
      - paramiko ==2.7.1
      - parso ==0.7.0
      - patchelf ==0.11  # [linux]
      - pbr ==5.4.5
      - pcre ==8.44
      - pexpect ==4.8.0
      - pickleshare ==0.7.5
      - pillow ==7.2.0
      - pip ==20.1.1
      - pkginfo ==1.5.0.1
      - pluggy ==0.13.1
      - prometheus_client ==0.8.0
      - prompt_toolkit ==3.0.5
      - psutil ==5.7.0
      - ptyprocess ==0.6.0
      - py ==1.9.0
      - py-lief ==0.10.1
      - pycodestyle ==2.6.0
      - pycosat ==0.6.3
      - pycparser ==2.20
      - pycrypto ==2.6.1
      - pyflakes ==2.2.0
      - pygments ==2.6.1
      - pyjwt ==1.7.1
      - pylint ==2.5.3
      - pynacl ==1.4.0
      - pyopenssl ==19.1.0
      - pyparsing ==2.4.7
      - pyqt ==5.9.2
      - pyrsistent ==0.16.0
      - pysocks ==1.7.1
      - pytables ==3.6.1
      - pytest ==5.4.3
      - python ==3.8.3
      - python-dateutil ==2.8.1
      - python-docx ==0.8.10
      - python-libarchive-c ==2.9
      - pytz ==2020.1
      - pyyaml ==5.3.1
      - pyzmq ==19.0.1
      - qt ==5.9.7
      - qtconsole ==4.7.5
      - qtpy ==1.9.0
      - readline ==8.0
      - requests ==2.24.0
      - requests-oauthlib ==1.3.0
      - requests-toolbelt ==0.9.1
      - ripgrep ==11.0.2
      - rope ==0.17.0
      - ruamel_yaml ==0.15.87
      - scikit-learn ==0.23.1
      - scipy ==1.5.0
      - send2trash ==1.5.0
      - setuptools ==49.2.0
      - setuptools-scm ==4.1.2
      - setuptools_scm ==4.1.2
      - sherpa ==4.12.1
      - sip ==4.19.8  # [osx]
      - sip ==4.19.8  # [osx]
      - six ==1.15.0
      - smmap ==3.0.2
      - snappy ==1.1.8
      - snowballstemmer ==2.0.0
      - soupsieve ==2.0.1
      - sphinx ==3.1.2
      - sphinxcontrib-applehelp ==1.0.2
      - sphinxcontrib-devhelp ==1.0.2
      - sphinxcontrib-htmlhelp ==1.0.3
      - sphinxcontrib-jsmath ==1.0.1
      - sphinxcontrib-qthelp ==1.0.3
      - sphinxcontrib-serializinghtml ==1.1.4
      - sqlite ==3.32.3
      - sqlparse ==0.3.1
      - tbb ==2020.0
      - terminado ==0.8.3
      - testpath ==0.4.4
      - threadpoolctl ==2.1.0
      - tk ==8.6.10
      - toml ==0.10.1
      - tornado ==6.0.4
      - tqdm ==4.47.0
      - traitlets ==4.3.3
      - typing_extensions ==3.7.4.2
      - urllib3 ==1.25.9
      - wcwidth ==0.2.5
      - webencodings ==0.5.1
      - wheel ==0.34.2
      - widgetsnbextension ==3.5.1
      - wrapt ==1.11.2
      - xz ==5.2.5
      - yaml ==0.2.5
      - zeromq ==4.3.2
      - zipp ==3.1.0
      - zlib ==1.2.11
      - zstd ==1.4.5
