package:
  name: ska3-core-latest
  version: 2020.1

build:
  noarch: generic

requirements:
  run:
   # - sherpa (not yet for Python 3.8)
   - astropy
   - beautifulsoup4
   - bokeh
   - cython
   - django >3.0
   # - git
   - gitpython
   - h5py
   # - hdf5
   - ipython
   - jinja2
   - jupyter
   # - jupyter_client
   # - jupyter_console
   - line_profiler
   - lxml
   - matplotlib
   - nb_conda
   - nbconvert
   - networkx
   - notebook
   - numba
   - numexpr
   - numpy
   - numpydoc
   # - openssl
   - pandas
   - autopep8
   - pillow
   # - pip
   - flake8
   - pylint
   - pyyaml
   - qt
   # - qtconsole
   # - readline
   - requests
   # - runipy
   - scikit-learn
   - scipy
   # - setuptools
   - six
   - sphinx
   # - sqlite
   # - tk
   - yaml
   # - zeromq
