package:
  name: chandra_aca
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python

source:
  path: {{ SKA_TOP_SRC_DIR }}/chandra_aca


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - six
    - numpy
    - chandra.time
    - quaternion
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - testr
    - numba
    - scipy
    - chandra.time
    - ska.numpy
    - quaternion
    - astropy
    - agasc
    - ska.quatutil
    - matplotlib
    - six


test:
  requires:
    - mica
  imports:
    - chandra_aca


about:
  home: https://github.com/sot/chandra_aca

