package:
  name: ska3-pinned
  version: 2018.07.24

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python ==3.8.1
    - numpy ==1.18.1
