package:
  name: ska3-core
  version: 2018.07.16

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
   - html5lib
   - libsodium
   - zeromq
   - alabaster ==0.7.10
   - asn1crypto ==0.22.0
   - astroid ==1.5.3
   - astropy ==2.0.1
   - babel ==2.5.0
   - beautifulsoup4 ==4.6.0
   - bleach ==1.5.0
   - certifi ==2016.2.28
   - cffi ==1.9.1
   - chardet ==3.0.4
   - configobj ==5.0.6
   - cryptography ==1.8.1
   - curl ==7.54.1
   - cycler ==0.10.0
   - cython ==0.26
   - db ==5.3.28
   - decorator ==4.1.2
   - django ==1.11.3
   - docutils ==0.14
   - entrypoints ==0.2.3
   - expat ==2.1.0
   - fontconfig ==2.12.1
   - freetype ==2.5.5
   - git ==2.11.1
   - glib ==2.50.2
   - h5py ==2.7.0
   - hdf5 ==1.8.17
   - icu ==54.1
   - idna ==2.2
   - imagesize ==0.7.1
   - ipykernel ==4.6.1
   - ipyparallel ==6.0.2
   - ipython ==6.1.0
   - ipython_genutils ==0.2.0
   - ipywidgets ==6.0.0
   - isort ==4.2.15
   - jbig ==2.1
   - jedi ==0.10.2
   - jinja2 ==2.9.6
   - jpeg ==9b
   - jsonschema ==2.6.0
   - jupyter ==1.0.0
   - jupyter_client ==5.1.0
   - jupyter_console ==5.2.0
   - jupyter_core ==4.3.0
   - krb5 ==1.13.2
   - lazy-object-proxy ==1.3.1
   - libffi ==3.2.1
   - libgcc ==4.8.5
   - libgfortran ==3.0.0
   - libiconv ==1.14
   - libpng ==1.6.30
   - libssh2 ==1.8.0
   - libtiff ==4.0.6
   - libxml2 ==2.9.4
   - libxslt ==1.1.29
   - line_profiler ==2.0
   - llvmlite ==0.18.0
   - lxml ==3.8.0
   - markupsafe ==1.0
   - matplotlib ==2.0.2
   - mistune ==0.7.4
   - mkl ==2017.0.3
   - mpi4py ==2.0.0
   - nbconvert ==5.2.1
   - nbformat ==4.4.0
   - networkx ==1.11
   - nose ==1.3.7
   - notebook ==5.0.0
   - numba ==0.33.0
   - numexpr ==2.6.2
   - numpy ==1.12.1
   - numpydoc ==0.7.0
   - olefile ==0.44
   - openssl ==1.0.2l
   - packaging ==16.8
   - pandas ==0.20.3
   - pandocfilters ==1.4.2
   - paramiko ==2.1.2
   - path.py ==10.3.1
   - pcre ==8.39
   - pep8 ==1.7.0
   - pexpect ==4.2.1
   - pickleshare ==0.7.4
   - pillow ==4.2.1
   - pip ==9.0.1
   - ply ==3.10
   - prompt_toolkit ==1.0.15
   - psutil ==5.2.2
   - ptyprocess ==0.5.2
   - py ==1.4.34
   - pyasn1 ==0.1.9
   - pycodestyle ==2.3.1
   - pycosat ==0.6.1
   - pycparser ==2.17
   - pycrypto ==2.6.1
   - pyflakes ==1.6.0
   - pygments ==2.2.0
   - pylint ==1.7.2
   - pyopenssl ==16.2.0
   - pyparsing ==2.2.0
   - pyqt ==5.6.0
   - pytables ==3.4.2
   - pytest ==3.2.1
   - python ==3.6.2
   - python-dateutil ==2.6.1
   - pytz ==2017.2
   - pyyaml ==3.12
   - pyzmq ==16.0.2
   - qt ==5.6.2
   - qtawesome ==0.4.4
   - qtconsole ==4.3.1
   - qtpy ==1.3.1
   - readline ==6.2
   - requests ==2.14.2
   - rope ==0.9.4
   - ruamel_yaml ==0.11.14
   - runipy ==0.1.5
   - scikit-learn ==0.19.0
   - scipy ==0.19.1
   - setuptools ==36.4.0
   - simplegeneric ==0.8.1
   - singledispatch ==3.4.0.3
   - sip ==4.18
   - six ==1.10.0
   - snowballstemmer ==1.2.1
   - sphinx ==1.6.3
   - sphinxcontrib ==1.0
   - sphinxcontrib-websupport ==1.0.1
   - spyder ==3.2.3
   - sqlalchemy ==1.1.13
   - sqlite ==3.13.0
   - terminado ==0.6
   - testpath ==0.3.1
   - tk ==8.5.18
   - tornado ==4.5.2
   - traitlets ==4.3.2
   - wcwidth ==0.1.7
   - wheel ==0.29.0
   - widgetsnbextension ==3.0.2
   - wrapt ==1.10.11
   - xz ==5.2.2
   - yaml ==0.1.6
   - zlib ==1.2.11
