package:
  name: chandra.time
  version:  {{ SKA_PKG_VERSION }}

build:
  preserve_egg_dir: yes # (default no)
  script: python setup.py install

source:
  path: {{ SKA_TOP_SRC_DIR }}/Chandra.Time

# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - cython >=0.20.1
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - numpy
    - testr

test:
  imports:
    - Chandra.Time


about:
  home: https://github.com/sot/Chandra.Time
  license: BSD
  summary: Chandra Time package
