name: Conda build release
on:
  release:
    types: [released, prereleased]

jobs:
  sanity_check:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.sanity_check.outputs.packages }}
      prerelease: ${{ steps.sanity_check.outputs.prerelease }}
    steps:
    - name: Checkout skare3
      uses: actions/checkout@v2
      with:
          path: skare3
    - name: Fetch Skare3 Tools
      uses: actions/checkout@v2
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - id: sanity_check
      run: |
        sudo pip3 install setuptools
        sudo pip3 install -r ./skare3_tools/requirements.txt
        sudo pip3 install ./skare3_tools
        skare3-release-check --skare3-path ./skare3 --version $GITHUB_REF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_API_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    needs: [sanity_check]
    steps:
    - name: Login to GitHub Package Registry
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Docker image
      run: docker pull docker.pkg.github.com/sot/skare3/centos5-builder:latest
    - name: Build
      id: build
      run: |
        [ "${{needs.sanity_check.outputs.prerelease}}" = "True" ] && OVERRIDE="--skare3-overwrite-version ${GITHUB_REF}" || OVERRIDE=""
        for package in ${{needs.sanity_check.outputs.packages}}; do
          docker run --rm  --name builder -v $GITHUB_WORKSPACE:/github/workspace -w /github/workspace \
                 -e CONDA_PASSWORD -e GIT_USERNAME -e GIT_PASSWORD \
                 docker.pkg.github.com/sot/skare3/centos5-builder:latest ${package} \
                 --tag ${GITHUB_SHA} --skare3-branch ${GITHUB_SHA} ${OVERRIDE};
        done;
        touch builds/linux-64/.empty
        touch builds/noarch/.empty
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: chandra-xray
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
        GIT_ASKPASS: /home/aca/git_pass.py
    - name: Save packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          builds/linux-64/
          builds/noarch/
          !builds/*/*repodata*
          !builds/*/index.html


  build-macos:
    runs-on: macos-latest
    name: Build on Mac OS
    needs: [sanity_check]
    steps:
    - name: Fetch Skare3 Tools
      uses: actions/checkout@v2
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - name: Build
      run: |
        source ./skare3_tools/actions/build/files/setup_conda.sh
        [ "${{needs.sanity_check.outputs.prerelease}}" = "True" ] && OVERRIDE="--skare3-overwrite-version ${GITHUB_REF}" || OVERRIDE=""
        for package in ${{needs.sanity_check.outputs.packages}}; do
          ./skare3_tools/actions/build/files/build.py ${package} \
          --tag ${GITHUB_SHA} --skare3-branch ${GITHUB_SHA} ${OVERRIDE};
        done;
        touch builds/osx-64/.empty
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USER: chandra-xray
        GIT_ASKPASS: skare3_tools/actions/build/files/git_pass.py
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
    - name: Save packages
      uses: actions/upload-artifact@v2
      with:
        name: packages-osx-64
        path: |
          builds/osx-64/
          !builds/*/*repodata*
          !builds/*/index.html


  update-channel:
    runs-on: head
    name: Update Conda Channel
    needs: [build-macos, build-linux]
    steps:
      - name: Get linux and noarch packages
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: packages
      - name: Get osx packages
        uses: actions/download-artifact@v2
        with:
          name: packages-osx-64
          path: packages/osx-64
      - name: Update channel
        run: |
          rsync -a packages/ ${CONDA_CHANNEL_DIR}
          for d in ${CONDA_CHANNEL_DIR}/*; do conda index $d; done;
        env:
          CONDA_CHANNEL_DIR: /proj/sot/ska/www/ASPECT/ska3-conda/test


  regression-test:
    runs-on: head
    name: Regression Tests
    needs: [sanity_check, update-channel]
    strategy:
      matrix:
        package: [ska3-flight, ska3-matlab]
    steps:
      - name: Regression Tests
        if: contains(needs.sanity_check.outputs.packages, matrix.package)
        run: |
          RELEASE_TAG=`basename "$GITHUB_REF"`
          conda create -y -n ${{ matrix.package }}-${RELEASE_TAG} \
                -c https://ska:${CONDA_PASSWORD}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/test \
                -c https://ska:${CONDA_PASSWORD}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/masters  \
                -c https://ska:${CONDA_PASSWORD}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/core-pkg-repo \
                -c https://ska:${CONDA_PASSWORD}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda \
                ${{ matrix.package }}==${RELEASE_TAG}
          source activate ${{ matrix.package }}-${RELEASE_TAG}
          cd /export/jgonzale/ska_testr
          run_testr --test-spec test_spec_SKA3_HEAD \
                    --outputs-dir /export/jgonzale/ska_testr/release_tests
          # skare3-test-results /export/jgonzale/ska_testr/release_tests/last/logs
          # add test result report to PR description
        env:
          CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
          SKA: /proj/sot/ska